
package com.google.code.bing.webservices.schema.imageryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IImageryService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts")
public interface IImageryService {


    /**
     * 
     * @param request
     * @return
     *     returns com.google.code.bing.webservices.schema.imageryservice.ImageryMetadataResponse
     * @throws IImageryServiceGetImageryMetadataResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "GetImageryMetadata", action = "http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetImageryMetadata")
    @WebResult(name = "GetImageryMetadataResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts")
    @RequestWrapper(localName = "GetImageryMetadata", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts", className = "com.google.code.bing.webservices.schema.imageryservice.GetImageryMetadata")
    @ResponseWrapper(localName = "GetImageryMetadataResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts", className = "com.google.code.bing.webservices.schema.imageryservice.GetImageryMetadataResponse")
    public ImageryMetadataResponse getImageryMetadata(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts")
        ImageryMetadataRequest request)
        throws IImageryServiceGetImageryMetadataResponseSummaryFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.google.code.bing.webservices.schema.imageryservice.MapUriResponse
     * @throws IImageryServiceGetMapUriResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "GetMapUri", action = "http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetMapUri")
    @WebResult(name = "GetMapUriResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts")
    @RequestWrapper(localName = "GetMapUri", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts", className = "com.google.code.bing.webservices.schema.imageryservice.GetMapUri")
    @ResponseWrapper(localName = "GetMapUriResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts", className = "com.google.code.bing.webservices.schema.imageryservice.GetMapUriResponse")
    public MapUriResponse getMapUri(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery/contracts")
        MapUriRequest request)
        throws IImageryServiceGetMapUriResponseSummaryFaultFaultMessage
    ;

}
