
package net.virtualearth.dev.webservices.v1.geocode;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GeocodeService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode", wsdlLocation = "http://dev.virtualearth.net/webservices/v1/metadata/geocodeservice/geocodeservice.wsdl")
public class GeocodeService
    extends Service
{

    private final static URL GEOCODESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.virtualearth.dev.webservices.v1.geocode.GeocodeService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.virtualearth.dev.webservices.v1.geocode.GeocodeService.class.getResource(".");
            url = new URL(baseUrl, "http://dev.virtualearth.net/webservices/v1/metadata/geocodeservice/geocodeservice.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://dev.virtualearth.net/webservices/v1/metadata/geocodeservice/geocodeservice.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GEOCODESERVICE_WSDL_LOCATION = url;
    }

    public GeocodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeocodeService() {
        super(GEOCODESERVICE_WSDL_LOCATION, new QName("http://dev.virtualearth.net/webservices/v1/geocode", "GeocodeService"));
    }

    /**
     * 
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "BasicHttpBinding_IGeocodeService")
    public IGeocodeService getBasicHttpBindingIGeocodeService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "BasicHttpBinding_IGeocodeService"), IGeocodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "BasicHttpBinding_IGeocodeService")
    public IGeocodeService getBasicHttpBindingIGeocodeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "BasicHttpBinding_IGeocodeService"), IGeocodeService.class, features);
    }

    /**
     * 
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "CustomBinding_IGeocodeService")
    public IGeocodeService getCustomBindingIGeocodeService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "CustomBinding_IGeocodeService"), IGeocodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "CustomBinding_IGeocodeService")
    public IGeocodeService getCustomBindingIGeocodeService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "CustomBinding_IGeocodeService"), IGeocodeService.class, features);
    }

}
