
package net.virtualearth.dev.webservices.v1.geocode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "GeocodeService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode", wsdlLocation = "http://dev.virtualearth.net/webservices/v1/metadata/geocodeservice/geocodeservice.wsdl")
public class GeocodeService
    extends Service
{

    private final static URL GEOCODESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://dev.virtualearth.net/webservices/v1/metadata/geocodeservice/geocodeservice.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        GEOCODESERVICE_WSDL_LOCATION = url;
    }

    public GeocodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeocodeService() {
        super(GEOCODESERVICE_WSDL_LOCATION, new QName("http://dev.virtualearth.net/webservices/v1/geocode", "GeocodeService"));
    }

    /**
     * 
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "BasicHttpBinding_IGeocodeService")
    public IGeocodeService getBasicHttpBindingIGeocodeService() {
        return (IGeocodeService)super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "BasicHttpBinding_IGeocodeService"), IGeocodeService.class);
    }

    /**
     * 
     * @return
     *     returns IGeocodeService
     */
    @WebEndpoint(name = "CustomBinding_IGeocodeService")
    public IGeocodeService getCustomBindingIGeocodeService() {
        return (IGeocodeService)super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/geocode", "CustomBinding_IGeocodeService"), IGeocodeService.class);
    }

}
