
package net.virtualearth.dev.webservices.v1.geocode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IGeocodeService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts")
public interface IGeocodeService {


    /**
     * 
     * @param request
     * @return
     *     returns net.virtualearth.dev.webservices.v1.geocode.GeocodeResponse
     * @throws IGeocodeServiceGeocodeResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "Geocode", action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geocode")
    @WebResult(name = "GeocodeResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts")
    @RequestWrapper(localName = "Geocode", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts", className = "net.virtualearth.dev.webservices.v1.geocode.contracts.Geocode")
    @ResponseWrapper(localName = "GeocodeResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts", className = "net.virtualearth.dev.webservices.v1.geocode.contracts.GeocodeResponse")
    public GeocodeResponse geocode(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts")
        GeocodeRequest request)
        throws IGeocodeServiceGeocodeResponseSummaryFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns net.virtualearth.dev.webservices.v1.geocode.GeocodeResponse
     * @throws IGeocodeServiceReverseGeocodeResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "ReverseGeocode", action = "http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/ReverseGeocode")
    @WebResult(name = "ReverseGeocodeResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts")
    @RequestWrapper(localName = "ReverseGeocode", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts", className = "net.virtualearth.dev.webservices.v1.geocode.contracts.ReverseGeocode")
    @ResponseWrapper(localName = "ReverseGeocodeResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts", className = "net.virtualearth.dev.webservices.v1.geocode.contracts.ReverseGeocodeResponse")
    public GeocodeResponse reverseGeocode(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/geocode/contracts")
        ReverseGeocodeRequest request)
        throws IGeocodeServiceReverseGeocodeResponseSummaryFaultFaultMessage
    ;

}
