
package net.virtualearth.dev.webservices.v1.search;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISearchService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search/contracts")
public interface ISearchService {


    /**
     * 
     * @param request
     * @return
     *     returns net.virtualearth.dev.webservices.v1.search.SearchResponse
     * @throws ISearchServiceSearchResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "Search", action = "http://dev.virtualearth.net/webservices/v1/search/contracts/ISearchService/Search")
    @WebResult(name = "SearchResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search/contracts")
    @RequestWrapper(localName = "Search", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search/contracts", className = "net.virtualearth.dev.webservices.v1.search.contracts.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search/contracts", className = "net.virtualearth.dev.webservices.v1.search.contracts.SearchResponse")
    public SearchResponse search(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search/contracts")
        SearchRequest request)
        throws ISearchServiceSearchResponseSummaryFaultFaultMessage
    ;

}
