
package net.virtualearth.dev.webservices.v1.search;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SearchService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search", wsdlLocation = "http://dev.virtualearth.net/webservices/v1/metadata/searchservice/dev.virtualearth.net.webservices.v1.search.wsdl")
public class SearchService
    extends Service
{

    private final static URL SEARCHSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://dev.virtualearth.net/webservices/v1/metadata/searchservice/dev.virtualearth.net.webservices.v1.search.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        SEARCHSERVICE_WSDL_LOCATION = url;
    }

    public SearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService() {
        super(SEARCHSERVICE_WSDL_LOCATION, new QName("http://dev.virtualearth.net/webservices/v1/search", "SearchService"));
    }

    /**
     * 
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISearchService")
    public ISearchService getBasicHttpBindingISearchService() {
        return (ISearchService)super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "BasicHttpBinding_ISearchService"), ISearchService.class);
    }

    /**
     * 
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "CustomBinding_ISearchService")
    public ISearchService getCustomBindingISearchService() {
        return (ISearchService)super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "CustomBinding_ISearchService"), ISearchService.class);
    }

}
