
package net.virtualearth.dev.webservices.v1.search;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SearchService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/search", wsdlLocation = "http://dev.virtualearth.net/webservices/v1/metadata/searchservice/dev.virtualearth.net.webservices.v1.search.wsdl")
public class SearchService
    extends Service
{

    private final static URL SEARCHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.virtualearth.dev.webservices.v1.search.SearchService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.virtualearth.dev.webservices.v1.search.SearchService.class.getResource(".");
            url = new URL(baseUrl, "http://dev.virtualearth.net/webservices/v1/metadata/searchservice/dev.virtualearth.net.webservices.v1.search.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://dev.virtualearth.net/webservices/v1/metadata/searchservice/dev.virtualearth.net.webservices.v1.search.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SEARCHSERVICE_WSDL_LOCATION = url;
    }

    public SearchService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchService() {
        super(SEARCHSERVICE_WSDL_LOCATION, new QName("http://dev.virtualearth.net/webservices/v1/search", "SearchService"));
    }

    /**
     * 
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISearchService")
    public ISearchService getBasicHttpBindingISearchService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "BasicHttpBinding_ISearchService"), ISearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "BasicHttpBinding_ISearchService")
    public ISearchService getBasicHttpBindingISearchService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "BasicHttpBinding_ISearchService"), ISearchService.class, features);
    }

    /**
     * 
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "CustomBinding_ISearchService")
    public ISearchService getCustomBindingISearchService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "CustomBinding_ISearchService"), ISearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISearchService
     */
    @WebEndpoint(name = "CustomBinding_ISearchService")
    public ISearchService getCustomBindingISearchService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/search", "CustomBinding_ISearchService"), ISearchService.class, features);
    }

}
