
package com.google.code.bing.webservices.schema.routeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IRouteService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts")
public interface IRouteService {


    /**
     * 
     * @param request
     * @return
     *     returns com.google.code.bing.webservices.schema.routeservice.RouteResponse
     * @throws IRouteServiceCalculateRouteResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "CalculateRoute", action = "http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/CalculateRoute")
    @WebResult(name = "CalculateRouteResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts")
    @RequestWrapper(localName = "CalculateRoute", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts", className = "com.google.code.bing.webservices.schema.routeservice.CalculateRoute")
    @ResponseWrapper(localName = "CalculateRouteResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts", className = "com.google.code.bing.webservices.schema.routeservice.CalculateRouteResponse")
    public RouteResponse calculateRoute(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts")
        RouteRequest request)
        throws IRouteServiceCalculateRouteResponseSummaryFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.google.code.bing.webservices.schema.routeservice.MajorRoutesResponse
     * @throws IRouteServiceCalculateRoutesFromMajorRoadsResponseSummaryFaultFaultMessage
     */
    @WebMethod(operationName = "CalculateRoutesFromMajorRoads", action = "http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/CalculateRoutesFromMajorRoads")
    @WebResult(name = "CalculateRoutesFromMajorRoadsResult", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts")
    @RequestWrapper(localName = "CalculateRoutesFromMajorRoads", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts", className = "com.google.code.bing.webservices.schema.routeservice.CalculateRoutesFromMajorRoads")
    @ResponseWrapper(localName = "CalculateRoutesFromMajorRoadsResponse", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts", className = "com.google.code.bing.webservices.schema.routeservice.CalculateRoutesFromMajorRoadsResponse")
    public MajorRoutesResponse calculateRoutesFromMajorRoads(
        @WebParam(name = "request", targetNamespace = "http://dev.virtualearth.net/webservices/v1/route/contracts")
        MajorRoutesRequest request)
        throws IRouteServiceCalculateRoutesFromMajorRoadsResponseSummaryFaultFaultMessage
    ;

}
