
package net.virtualearth.dev.webservices.v1.imagery;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-hudson-208-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImageryService", targetNamespace = "http://dev.virtualearth.net/webservices/v1/imagery", wsdlLocation = "imageryservice.wsdl")
public class ImageryService
    extends Service
{

    private final static URL IMAGERYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.virtualearth.dev.webservices.v1.imagery.ImageryService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = net.virtualearth.dev.webservices.v1.imagery.ImageryService.class.getResource(".");
            url = new URL(baseUrl, "imageryservice.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'imageryservice.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMAGERYSERVICE_WSDL_LOCATION = url;
    }

    public ImageryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImageryService() {
        super(IMAGERYSERVICE_WSDL_LOCATION, new QName("http://dev.virtualearth.net/webservices/v1/imagery", "ImageryService"));
    }

    /**
     * 
     * @return
     *     returns IImageryService
     */
    @WebEndpoint(name = "BasicHttpBinding_IImageryService")
    public IImageryService getBasicHttpBindingIImageryService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/imagery", "BasicHttpBinding_IImageryService"), IImageryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IImageryService
     */
    @WebEndpoint(name = "BasicHttpBinding_IImageryService")
    public IImageryService getBasicHttpBindingIImageryService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/imagery", "BasicHttpBinding_IImageryService"), IImageryService.class, features);
    }

    /**
     * 
     * @return
     *     returns IImageryService
     */
    @WebEndpoint(name = "CustomBinding_IImageryService")
    public IImageryService getCustomBindingIImageryService() {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/imagery", "CustomBinding_IImageryService"), IImageryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IImageryService
     */
    @WebEndpoint(name = "CustomBinding_IImageryService")
    public IImageryService getCustomBindingIImageryService(WebServiceFeature... features) {
        return super.getPort(new QName("http://dev.virtualearth.net/webservices/v1/imagery", "CustomBinding_IImageryService"), IImageryService.class, features);
    }

}
